# Use Node.js base image
FROM node:23-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . .

# Expose the service port
EXPOSE 7703

# Build, compile TypeScript -> CommonJS
RUN npm run build

# Start the service
CMD ["npm","run", "start"]
