services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - microservices-network
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./gateway-service
    ports:
      - "7700:7700"
    depends_on:
      - user-service
      - booking-service
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    ports:
      - "7701:7701"
    environment:
      - DB_URI=mongodb+srv://emilfroding:asd123@scaledb.tql8n.mongodb.net/Hotel-404?retryWrites=true&w=majority&appName=ScaleDb

    depends_on:
      - mongo
    networks:
      - microservices-network

  booking-service:
    build: ./booking-service
    ports:
      - "7702:7702"
    environment:
      - DB_URI=mongodb+srv://emilfroding:asd123@scaledb.tql8n.mongodb.net/Hotel-404?retryWrites=true&w=majority&appName=ScaleDb
    depends_on:
      - mongo
    networks:
      - microservices-network

networks:
  microservices-network:

volumes:
  mongo-data:
