apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container-hotel
          image: hotelacr12345.azurecr.io/hotel-service:latest
          ports:
          - containerPort: 7703
          resources:
            requests:   
              cpu: "250m"
              memory: "256Mi"
            limits:   
              cpu: "500m"
              memory: "512Mi"
          startupProbe:      
            httpGet:
              path: /startup
              port: 7703
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 7703
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /liveness
              port: 7703
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3