apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: hotelacr12345.azurecr.io/hotel-service:latest  # Direkt använd "latest"
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
