apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container-hotel
          image: hotelacr12345.azurecr.io/hotel-service:latest
          ports:
            - containerPort: 7073
