apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-microservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-deployment-hotel  # Make sure this matches your Deployment name
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 5  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale up when CPU usage exceeds 50%
