name: CI/CD for My Microservice

on:
  pull_request:
    branches:
      - master # Adjust if using a different branch
  push:
    branches:
      - master

permissions:
  id-token: write # This grants the workflow the permission to generate the ID token
  contents: read

jobs:
  testJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tests for hotel-service
        run: |
          cd backend/hotel-service
          npm install
          npm test

      - name: Run tests for user-service
        run: |
          cd backend/user-service
          npm install
          npm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: testJob
    if: github.event_name == 'push' # Runs only on push to master

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # COMMENT: Ensure that myregistry.azurecr.io is replaced with your actual Azure Container Registry URL.
      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login hotelacr12345.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: (hotel-service) Build and Tag Docker Image 1
        run: |
          cd backend/hotel-service  
          docker build -t hotelacr12345.azurecr.io/hotel-service:${{ github.sha }} .
          docker tag hotelacr12345.azurecr.io/hotel-service:${{ github.sha }} hotelacr12345.azurecr.io/hotel-service:latest

      - name: (hotel-service) Push Docker Image to Azure Container Registry
        run: |
          docker push hotelacr12345.azurecr.io/hotel-service:${{ github.sha }}
          docker push hotelacr12345.azurecr.io/hotel-service:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: config something
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Expands the manifest YAML file (i.e. replaces placeholders in the YAML file with environment variable values)
      # and deploys the microservice to the Azure Kubernetes Service (AKS) cluster.
      - name: Deploy1
        run: envsubst < ./kubernetes/deploy.yaml | kubectl apply -f -
