name: CI/CD for My Microservice

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # COMMENT: Ensure that myregistry.azurecr.io is replaced with your actual Azure Container Registry URL.
      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login myregistry.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin
    
      - name: (hotel-service) Build and Tag Docker Image 1
        run: |
          cd backend/hotel-service  
          docker build -t myregistry.azurecr.io/hotel-service:${{ github.sha }} .
          docker tag myregistry.azurecr.io/hotel-service:${{ github.sha }} myregistry.azurecr.io/hotel-service:latest

      - name: (user-service) Build and Tag Docker Image 2
        run: |
          cd backend/user-service  
          docker build -t myregistry.azurecr.io/user-service:${{ github.sha }} .
          docker tag myregistry.azurecr.io/user-service:${{ github.sha }} myregistry.azurecr.io/user-service:latest
          
      - name: (booking-service) Build and Tag Docker Image 3
        run: |
          cd backend/booking-service  
          docker build -t myregistry.azurecr.io/booking-service:${{ github.sha }} .
          docker tag myregistry.azurecr.io/booking-service:${{ github.sha }} myregistry.azurecr.io/booking-service:latest

      - name: (hotel-service) Push Docker Image to Azure Container Registry
        run: |
          docker push myregistry.azurecr.io/hotel-service:${{ github.sha }}
          docker push myregistry.azurecr.io/hotel-service:latest
          
      - name: (user-service) Push Docker Image to Azure Container Registry
        run: |
          docker push myregistry.azurecr.io/user-service:${{ github.sha }}
          docker push myregistry.azurecr.io/user-service:latest

      - name: (booking-service) Push Docker Image to Azure Container Registry
        run: |
          docker push myregistry.azurecr.io/booking-service:${{ github.sha }}
          docker push myregistry.azurecr.io/booking-service:latest
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group my-resource-group --name my-aks-cluster
        # COMMENT: Change the resource group and AKS cluster name to match your Azure setup.

      - name: (hotel-service) Deploy to AKS 
        run: |
          kubectl set image deployment/hotel-service-deployment my-container=myregistry.azurecr.io/hotel-service:${{ github.sha }}
          # COMMENT: Make sure that hotel-service-deployment exists in your Kubernetes cluster and corresponds to the correct microservice.
          kubectl rollout status deployment/hotel-service-deployment

      - name: (user-service) Deploy to AKS
        run: |
          kubectl set image deployment/user-service-deployment my-container=myregistry.azurecr.io/user-service:${{ github.sha }}
          # COMMENT: Ensure user-service-deployment exists in your Kubernetes cluster and corresponds to the correct microservice.
          kubectl rollout status deployment/user-service-deployment
       
      - name: (booking-service) Deploy to AKS
        run: |
          kubectl set image deployment/booking-service-deployment my-container=myregistry.azurecr.io/booking-service:${{ github.sha }}
          # COMMENT: Ensure booking-service-deployment exists in your Kubernetes cluster and corresponds to the correct microservice.
          kubectl rollout status deployment/booking-service-deployment


