name: CI/CD for My Microservice

on:
  pull_request:
    branches:
      - master  # Adjust if using a different branch
  push:
    branches:
      - master
      
permissions:
  id-token: write   # This grants the workflow the permission to generate the ID token
  contents: read  

  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # COMMENT: Ensure that myregistry.azurecr.io is replaced with your actual Azure Container Registry URL.
      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login hotelacr12345.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin
    
      - name: (hotel-service) Build and Tag Docker Image 1
        run: |
          cd backend/hotel-service  
          docker build -t hotelacr12345.azurecr.io/hotel-service:${{ github.sha }} .
          docker tag hotelacr12345.azurecr.io/hotel-service:${{ github.sha }} hotelacr12345.azurecr.io/hotel-service:latest

      - name: (hotel-service) Push Docker Image to Azure Container Registry
        run: |
          docker push hotelacr12345.azurecr.io/hotel-service:${{ github.sha }}
          docker push hotelacr12345.azurecr.io/hotel-service:latest
          

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group hotelResourceGroup --name hotelAKSCluster
  
      - name: Verify Kubernetes Authentication
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods --all-namespaces
  
      - name: (hotel-service) Deploy to AKS
        run: |
          kubectl set image deployment/hotel-service-deployment my-container=hotelacr12345.azurecr.io/hotel-service:${{ github.sha }}
          kubectl rollout status deployment/hotel-service-deployment
